services:
  runner:
    image: ghcr.io/actions/actions-runner:latest

    environment:
      # — Required —
      ACCESS_TOKEN: ${ACCESS_TOKEN:?ACCESS_TOKEN is required}

      # — One of these scopes must be set —
      ORG: ${ORG:-}
      REPO: ${REPO:-}
      ENTERPRISE: ${ENTERPRISE:-}

      # — Optional —
      LABELS: ${LABELS:-self-hosted,ephemeral}
      RUNNER_WORKDIR: /tmp/_work

    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro # Mount your local script

    entrypoint: ["/entrypoint.sh"]
    restart: "no"
